Rewrite with functions and add support for Cylc 8 log paths.

diff --git a/app/process_logs/bin/archive_logs b/app/process_logs/bin/archive_logs
--- a/app/process_logs/bin/archive_logs
+++ b/app/process_logs/bin/archive_logs
@@ -1,62 +1,102 @@
 #!/usr/bin/bash
 
-# Archive log directories to Jasmin.
-#
-# Based on suites listed in status CSV.
-# Use rsync which works well when synching a large number of small files.
-# Try and archive each suite in the list, but keep track of failures.
-# Then exit with success only if no errors occur.
+# Check required env vars set correctly
+# To do: check vars set 
+check_env_vars() {	
+  if [[ ! -f $SUITE_STATUS ]]; then 
+    echo "Error: Suite status file $SUITE_STATUS does not exist" >&2
+    exit 99
+  fi
+  echo "Suite status: $SUITE_STATUS"
+  echo "Archive dir: $ARCHIVE_DIR"
+  echo "Remote host: $REMOTE_HOST"
+  echo "Copy command: $COPY_CMD"
+}
 
-echo "Suite status: $SUITE_STATUS"
-echo "Archive dir: $ARCHIVE_DIR"
-echo "Remote host: $REMOTE_HOST"
-echo "Copy command: $COPY_CMD"
+# Check if suite is to be archived, and that dir exists
+check_archiving() {
+  if [[ "$RETRIEVE_LOGS" == "False" ]]; then
+    return 1
+  fi
+  if [[ ! -d $SUITE_DIR ]]; then
+	echo "Error: $SUITE_DIR does not exist" >&2
+	((ERR_COUNT+=1))
+	return 1
+  fi 
+}
 
-# Check we can read suite status file
-if [ ! -f $SUITE_STATUS ]; then
-    echo "Error: Can't find suite status file: $SUITE_STATUS"
-    exit 1
-fi
+# Check Cylc version for suite 
+check_cylc7() {
+  if [[ "$CYLC8" == "True" ]]; then
+	echo "Suite "$SUITE" is running under Cylc 8" >&2
+    ((ERR_COUNT+=1))
+	return 1
+  fi
+}
 
-# Keep track of the number of failures
-err_count=0
+# Get log directory for Cylc 7 based on log symlink
+get_log_dir_cylc7() {
+  if [[ -L log ]] && [[ -e log ]]; then		
+    LOG_DIR=$(readlink log)
+  else 
+  	echo "Error: $SUITE_DIR/log symlink does not exist" >&2
+	((ERR_COUNT+=1))
+    return 1
+  fi
+}
 
-# Read status CSV columns 1, 2 and 6 (Suite id, User, Retrieve logs)
-while IFS="," read -r suite user retr
-do
-	
-    # Check if logs need to be retrieved
-    if [[ "$retr" == "True" ]];
-    then
+# Get log directory for Cylc 8 based on specified run
+get_log_dir_cylc8() {
+  LOG_DIR=run$RUN/log
+  if [[ ! -d "$LOG_DIR" ]]; then 
+	echo "Error: $LOG_DIR does not exist" >&2
+	((ERR_COUNT+=1))
+    return 1
+  fi 
+} 
 
-	# Check log dir exists
-	dir="/home/n02/n02/$user/cylc-run/$suite"
-	if [[ -d "$dir" ]];
-	then
+# Get log directory
+get_log_dir() {
+  cd $SUITE_DIR
+  if [[ "$CYLC8" == "True" ]]; then
+    get_log_dir_cylc8
+  else
+	get_log_dir_cylc7
+  fi
+}
 
-	    # Make sure target dir exists on Jamsin
-	    #ssh -n $REMOTE_HOST "mkdir -p $ARCHIVE_DIR/$suite"
+# Run the transfer command.
+transfer_files() {
+  echo "Archiving $SUITE_DIR/$LOG_DIR"
+  $COPY_CMD $SUITE_DIR/$LOG_DIR/ $REMOTE_HOST:$ARCHIVE_DIR/$SUITE/$LOG_DIR || ((ERR_COUNT+=1))
+} 
 
-	    # Get current log directory
-	    cd $dir
-	    logdir=$(readlink log)
-
-	    # Transfer the files
-	    echo "Archiving $dir/$logdir/"
-	    $COPY_CMD $dir/$logdir/ $REMOTE_HOST:$ARCHIVE_DIR/$suite/$logdir || ((err_count+=1))
-
-        else
-	    echo "Error: $dir does not exist" >&2
-	    ((err_count+=1))
-	fi
-
-    fi
-done <  <(cut -d "," -f1,2,6 $SUITE_STATUS | tail -n +2)
+# Loop though suites in status CSV and archive log dirs
+archive_suite_logs() {	
+  ERR_COUNT=0
+  while IFS="," read -r SUITE USER RETRIEVE_LOGS CYLC8 RUN; do
+	SUITE_DIR="/home/n02/n02/$USER/cylc-run/$SUITE"
+    check_archiving || continue
+	get_log_dir || continue
+	transfer_files
+  done <  <(cut -d "," -f1,2,6,16,17 $SUITE_STATUS | tail -n +2)
+} 
 
 # Report status
-echo "Info: Failures in archiving $err_count suite log directories." >&2
-exit $err_count
+error_report() {
+  echo "Info: Failures in archiving $ERR_COUNT suite log directories." >&2
+  exit $ERR_COUNT	
+}
 
+# Archive log directories to Jasmin.
+# Based on suites listed in status CSV.
+# Should use rsync which works well when synching a large number of small files.
+# Try and archive each suite in the list, but keep track of failures.
+# Then exit with success only if no errors occur.
+main() {
+  check_env_vars
+  archive_suite_logs
+  error_report 
+}
 
-
-
+main "$@"
