Tidy up scripts.

diff --git a/app/process_logs/bin/get_cylc_times b/app/process_logs/bin/get_cylc_times
--- a/app/process_logs/bin/get_cylc_times
+++ b/app/process_logs/bin/get_cylc_times
@@ -40,7 +40,7 @@ check_cycle() {
   local pattern='^[0-9]{8}T[0-9]{4}Z$'
   
   # Get first element of line
-  start=$(sed -n "${line}p" < $OUT_FILE | cut -f1 -d,)
+  local start=$(sed -n "${line}p" < $OUT_FILE | cut -f1 -d,)
   if [[ $start =~ $pattern ]]; then 
     echo $start 
   else 
@@ -154,7 +154,7 @@ parse_args() {
   INCR=$4
   
   if [ ! -d $LOG_DIR ]; then 
-    echo "Error: Log dir $LOG_DIR does not exist"
+    echo "Error: Log dir $LOG_DIR does not exist" >&2
     exit 1
   fi  
   if [[ "$INCR" != "True" && "$INCR" != "False" ]]; then 
